name: e_commerce
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.6 <4.0.0"

#---------PACKAGES---------#
dependencies:
  get_storage: ^2.1.1

  flutter:
    sdk:
      flutter

      # Utility Packages
  http: ^1.2.1
  intl: ^0.19.0
  logger: ^2.0.1
  url_launcher: ^6.1.12

# Icons
iconsax: ^0.0.8
cupertino_icons: ^1.0.2

# State management
get: ^4.6.5
get_storage: ^2.1.1

# Product Specific

#-----./ Packages END -------#

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1
  flutter_native_splash: ^2.3.2

flutter:
  uses-material-design: true

  #----LOCAL ASSETS-----#
  assets:
    - asset\logo\
    - asset\images\
    - asset\icons\
